.PHONY : test_hist test_progressbar

test_hist: test_hist.cc
	@g++ test_hist.cc ../src/utils/general_utils.cc -o test_hist
	@./test_hist

test_progressbar: test_progressbar.cc
	@g++ test_progressbar.cc ../src/utils/general_utils.cc -o test_progressbar
	@./test_progressbar
